---
name: 'myconn'
configurationClass:
  name: 'H2ExampleConfiguration'
  package: 'com.exclamationlabs.connid.base.h2example.configuration'
rest: true # io-error-retries
results: true
service: true # service-url
custom:
  items:
    optional:
      mine1:
        type: int # Message.properties connector.myconn.my-type-1.help & connector.custom.my-type-1.display
        default: '1'
      mine2:
        type: boolean
        default: 'true'
      mine21:
        type: long
        default: '123456789'
      mine4:
        type: string
        default: 'hi'
    required:
      mine5:
        type: string # subset of string
        default: 'hi@hi.com'
      mine6:
        type: string # subset of string
        default: 'http://www.google.com'
      mine7:
        type: string
        default: '2021-10-01'
      mine8:
        type: int
        validations:
          - '@Min(20)'
          - '@Max(30)'
  helpText:
    serviceUrl:
      display: 'My Service URL'
      help: 'My Service Help'
    security:
      httpBasicAuthUsername:
        display: 'something.displayme'
        help: 'something.helpme'
